version: "2"

services:

  site1:
    image: python:3.7
    volumes:
      - ./site1:/srv/app
    networks:
      - sites
    command: ["python3", "-m", "http.server", "--directory", "/srv/app"]

  site2:
    image: python:3.7
    volumes:
      - ./site2:/srv/app
    networks:
      - sites
    command: ["python3", "-m", "http.server", "--directory", "/srv/app"]

  nginx:
    image: nginx:1.17.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - sites

networks:
  sites:
